### PR TITLE
Game Additions Check description 

### PR DESCRIPTION
**Pull request by DevilGlitch**
- /binding-of-issac/index.html<br>
> Eaglercraft X (With Preloaded Server's Mod) (Minecraft 1.8 Multiplayer)<br>
   - /eagaler-x/index.html<br>
> Mini-agario<br>
   - /mini-agario/dots.html<br>
> Yohoho.io<br>
   - /yohoho/index.html<br>
> Paper.io 2<br>
   - /paperio2/index.html<br>
> Quake<br>
  - /quake/index.html<br>
> Super Mario 64<br>
  - /mario-64/index.html<br>
<br>
 -- / --
<br>

   - /m/nonproxied/downloadable/<br>
> WebRetro Popular Games Download Links<br>
   - /webretro/retro-p/DevilGlitch-Ret/<br>
 > Friday Night Funkin<br>
  - /fnf/

### CODE REVIEW

**Comment by MotorTruck1221** [comment]
I'll merge this. Just one question... what is all the temp.txt files?

**Comment by DevilGlitch** [comment]
> I'll merge this. Just one question... what is all the temp.txt files?

temp.txt is a file I use to make proper directories for files I'm uploading otherwise a lot of things break and files will start conflicting I usually try to delete them once Im done but I sometimes forget.

**Comment by MotorTruck1221** [comment]
Could you list all the games you added?

**Comment by MotorTruck1221** [comment]
> > I'll merge this. Just one question... what is all the temp.txt files?
> 
> temp.txt is a file I use to make proper directories for files I'm uploading otherwise a lot of things break and files will start conflicting I usually try to delete them once Im done but I sometimes forget.

Ah okay

**Comment by MotorTruck1221** [comment]
Merged

**Pull request merged**
